### ISSUE TITLE
docking 后窗口颜色有变化

### ISSUE THREAD

**Issue by BenzzzX** [ZhuRong-HomoStation/UEImgui#3]
![L$~I@TX9(9LWU6298Z`4@(R](https://user-images.githubusercontent.com/15247869/104448347-fd3e9a00-55d7-11eb-8842-4125a18001f6.png)

![31Z J`JZ6PHB07)UE}MXV$I](https://user-images.githubusercontent.com/15247869/104448350-ff085d80-55d7-11eb-81cc-84facdaf6080.png)

**Comment by zhurongjun** [comment]
如果Childbg Color为非透明色，在viewport中会直接覆盖窗口底色
